/**:
  ros__parameters:
    camera/autorecord: false                   # Enable autorecord at takeoff
    camera/disparity_image: false              # Enable disparity map image streaming
    camera/ev_compensation: 9                  # EV compensation: 0 = -3.00 EV; 3 = -2.00 EV; 6 = -1.00 EV; 9 = 0.00 EV; 12 = 1.00 EV; 15 = 2.00 EV; 18 = 3.00 EV
    camera/hdr: true                           # Enable HDR
    camera/max_zoom_speed: 10.0                # Max zoom speed (in tan(deg)/sec) [0.1, 10.0]
    camera/mode: 0                             # Camera mode: 0 = camera in recording mode, 1 = camera in photo mode
    camera/stereo/disparity_map: false         # Stream disparity map image (supported only by ANAFI Ai): true = enabled; false = disabled
    camera/stereo/obstacle_avoidance: true     # Enable obstacle avoidance (supported only by ANAFI Ai): true = enabled; false = disabled
    camera/streaming: 0                        # Streaming mode: 0 = minimize latency with average reliability (best for piloting); 1 = maximize the reliability with an average latency; 2 = maximize the reliability using a framerate decimation with an average latency
    camera/style: 0                            # Images style: 0 = natural look style; 1 = produces flat and desaturated images, best for post-processing; 2 = intense style: bright colors, warm shade, high contrast; 3 = pastel style: soft colors, cold shade, low contrast
    camera/thermal/rendering: 0                # Thermal image rendering mode: 0 = visible; 1 = thermal; 2: blended
    drone/banked_turn: false                   # Enable banked turn
    drone/camera_operated: false               # Commands are relative to the camera pitch
    drone/max_altitude: 2.0                    # Max altitude (in m) [0.5, 4000.0]
    drone/max_distance: 10.0                   # Max distance (in m) [10.0, 4000.0]
    drone/max_horizontal_speed: 1.0            # Max horizontal speed (in m/s) [0.1, 15.0]
    drone/max_pitch_roll: 10.0                 # Max pitch/roll (in deg) [1.0, 40.0]
    drone/max_pitch_roll_rate: 300.0           # Max pitch/roll rotation speed (in deg/s) [40.0, 300.0]
    drone/max_vertical_speed: 1.0              # Max vertical speed (in m/s) [0.1, 4.0]
    drone/max_yaw_rate: 180.0                  # Max yaw rotation speed (in deg/s) [3.0, 200.0]
    gimbal/max_speed: 180.0                    # Max gimbal speed (in deg/s) [1.0, 180.0]
    home/autotrigger: true                     # Enable auto trigger RTH
    home/ending_behavior: 1                    # Ending behavior for RTH: 0 = land after RTH; 1 = hover after RTH
    home/hovering_altitude: 10.0               # RTH ending hovering altitude (in m) [1.0, 10.0]
    home/min_altitude: 20.0                    # RTH minimum altitude (in m) [20.0, 100.0]
    home/precise: true                         # Enable precise RTH
    home/type: 4                               # Home type for RTH: 1 = return to the last takeoff location; 3 = return to a user-set custom location; 4 = return to the pilot position
    storage/download_folder: ~/Pictures/Anafi  # Absolute path to the download folder
